capellambse/extensions/reqif.py

This failed if the value already was the default.

Fix issue when updating a property with the default value

---

.github/workflows/build-test-publish.yml
setup.cfg

Releases are published on PyPI: https://pypi.org/project/capellambse/
Releases are created with any tag that starts with `v`. E.g. `v0.1.0`, `v0.0.1a1`.
See https://github.com/DSD-DBS/py-capellambse/actions/runs/1435034047 for a successful build.
For a real release all tests should pass. I disabled the windows build for testing purposes.
NB. Do not depend on version 0.0.1a1: will be removed at some point.

Release capellambse

---

capellambse/model/common/element.py

Having GenericElement as a hashable type (like `object`) allows us to work with sets of elements. We are not limited to using only lists.

Make GenericElement hashable

---

capellambse/loader/modelinfo.py
tests/test_model_layers.py

The properties of the `ModelInfo` objects (available e.g. as `MelodyModel.info`) are broken:
* `derive_version_url()` assumes that `url` points to a project on a Gitlab instance. We cannot simply make that assumption, and it breaks in several supported cases:
- Remote repos stored anywhere that's not a Gitlab instance will result in incorrect URLs.
- Local `file://` repositories or ones accessed over `ssh://` would result in a path that does not exist (however, see the next point as well).
* `url` is set to `None` when it's not an `https://` URL. This also breaks several different use cases:
- It prevents the `LocalFileHandler` from storing the `path` in that field, as it will never be an `https://` URL.
- Other URLs (e.g. `git+ssh://`, `git+file://`) are not saved.
* `as_dict()` is …

Remove broken and/or redundant logic from the `ModelInfo` object

---

capellambse/extensions/reqif.py
tests/test_reqif.py

Hashing only works if the `__eq__` and `__hash__` methods are defined in the same class.

Make RequirementType and EnumValue hashable

---

capellambse/model/crosslayer/fa.py
tests/data/melodymodel/5_0/Melody Model Test.aird
tests/data/melodymodel/5_0/Melody Model Test.capella
tests/test_model_layers.py

This pull-request makes the following additions:
Comparing with the LogicalLayer capabilities were also missing. FunctionalExchange lookup was named in alignment with the other layers:
- component_package
- capability_package
- all_capabilities
- all_function_exchanges
- allocating_component_exchange
- owner
- allocating_physical_path
- allocating_physical_link
- owner
- physical_paths
- physical_links
Please make sure to have a look at the `owner` property implementation. I tried to prepare write support by adding appropriate setters and deleters. I couldn't type annotate the owner attribute on the AbstractExchange class unfortunately. Mypy didn't let me.
The `owner.deleter` on the ComponentExchange is using the not yet implemented deleter of the `ReferenceSearchingAccessor`. What I …

Exchange trace pa

---

capellambse/model/crosslayer/__init__.py
capellambse/model/crosslayer/information/__init__.py
capellambse/model/crosslayer/information/datatype.py
capellambse/model/crosslayer/information/datavalue.py
capellambse/model/layers/oa.py

I'm late to the party but I got some cake:
After seeing the progress of our information.py in the crosslayer module I felt the urge to improve its structure and style consistency compared to the other layer implementations where I took part in. So we(@Wuestengecko and I) added functionality to the https://github.com/DSD-DBS/py-capellambse/blob/e45a071649a6f9feba4765c35c5575aca8fa15a1/capellambse/model/common/__init__.py#L51-L59 function such that it is able to resolve nested package structure. Therefore the xtype strings are not needed anymore iff there are class definitions in the right module in line with the xtype-string from capella. For e.g.: `"org.polarsys.capella.core.data.{module}.{submodule}.{subsubmodule}.{...}.{clsname}" is getting resolved.
Additionally the metamodel was …

Improve information

---

capellambse/model/crosslayer/capellacommon.py
tests/data/melodymodel/5_2/Melody Model Test.capella
tests/test_model_layers.py

This PR adds a new ModelObject called `GenericTrace` that can be added via the Wizards > Trace Manager option exposed when right clicking a ModelObject in the Project Explorer. 
As this is a very generic thing, an Acessor is set on the `GenericElement` and reveals a `.traces` attribute. We currently do not distinguish between incoming and outgoing traceability links.
@Wuestengecko I want to point out that the name property of this class is in a similar fashion like the recently added `FunctionalChainInvolvementLink` & `FunctionalChainInvolvementFunction`. Does it make sense to generalize this, to get drier or do you feel that this adds unnecessary complexity? I can think about a flexible function that gets a parameter `attr: str` and builds a name just like this.

Add traces attribute to GenericElement

---

capellambse/loader/filehandler/gitfilehandler.py

This PR implements the capability for the `git://` file handler to create and update shallow clones in its cache directory. This significantly reduces the network bandwidth and disk space needed for updating and maintaining the cache.
It also introduces the new file handler specific keyword argument `shallow=`, which controls this behavior. If it is set to `True` (the default), clones and fetches will be shallow, and existing full clones will be converted to shallow clones as they are accessed. If it is `False`, clones and fetches will fetch the full history. Existing shallow clones will however not be "unshallowed".
Note that actually unlinking unused objects is subject to git's garbage collection. To benefit from the disk space savings immediately, consider either wiping the cache or …

Shallow cloning functionality for the `git://` file handler

---

capellambse/extensions/reqif/elements.py
capellambse/loader/filehandler/gitfilehandler.py
capellambse/model/common/element.py

With this PR we are more safe during loader failures and the displayed representation of `reqif.ReqIFElement`s in the Terminal (and possibly Jupyter) is fixed. For the latter we simply had to add a `_short_repr_`. To stay dry we changed the signature of `_short_repr_` on `common.GenericElement` such that it can be reused.

Minor fixes

---

capellambse/loader/xmltools.py
capellambse/model/common/accessors.py
tests/test_reqif.py

This PR fixes the bug described in #108 but for the creation of all AttributeValues, not BooleanAttributeValue exclusively. In doing so it was revealed that handing over timezone unaware `datetime` objects doesn't lead to the supported format for writing to the xml. An extra test parameter was added where in this case the local timezone was added as tzinfo.

Fix creating model objects with explicit default values (#108)

---

capellambse/extensions/reqif/elements.py
tests/test_reqif.py

When there is no definition reference given, Capella displays AttributeValue elements with `[TYPE Value Attribute]` where the `TYPE` is exchanged with one of (Integer, String, Boolean,...). This commit implements this behavior and adds lines to `test_create_requirements_attributes`.

ReqIF Attribute Value default __repr__ behaviour

---

capellambse/extensions/reqif/elements.py

The `RequirementTypesFolder` can't be created underneath a `RequirementsModule`. But it can be moved there via the GUI. In this PR we added an Accessor to the `RequirementsModule` for `RequirementTypesFolder`s.

Add RequirementTypesFolder accessor to RequirementsModule

---

capellambse/extensions/reqif/elements.py
capellambse/model/__init__.py
capellambse/model/common/__init__.py
capellambse/model/common/accessors.py
capellambse/model/crosslayer/__init__.py
capellambse/model/crosslayer/capellacommon.py
capellambse/model/crosslayer/capellacore.py
capellambse/model/crosslayer/cs.py
capellambse/model/crosslayer/fa.py
capellambse/model/crosslayer/information/__init__.py
capellambse/model/crosslayer/information/datatype.py
capellambse/model/crosslayer/information/datavalue.py
capellambse/model/layers/ctx.py
capellambse/model/layers/la.py
capellambse/model/layers/oa.py
capellambse/model/layers/pa.py
tests/test_xlayer_cs.py

The `ProxyAccessor` has been split up into multiple different classes,
each taking over a part of the former `ProxyAccessor`'s
responsibilities:
- The `DirectProxyAccessor`, which handles the most common simple cases
- The `ReferencingProxyAccessor`, which handles the case where the child
elements in the tree are only references onto the actual elements, and
not the elements themselves (this takes away the `follow=` argument)
- The `DeepProxyAccessor`, which searches through an entire subtree
(this takes away the `deep=` argument)
This split simplifies the logic around the various `__get__` methods of
these accessors. It also allows to implement the different strategies
for the related `__set__` methods in a cleaner way in a future commit.
Be aware that the default value for …

Split up the ProxyAccessor

---

capellambse/aird/parser/__init__.py
capellambse/model/diagram.py
tests/data/melodymodel/5_0/Melody Model Test.aird
tests/data/melodymodel/5_2/Melody Model Test.aird
tests/test_model_layers.py

The `description` of `model.Diagram` instances was looked up in the
wrong place.
Fixes #125

Fix accessing `description` of Diagrams

---

capellambse/loader/core.py
tests/conftest.py
tests/data/melodymodel/5_0/Melody Model Test.capella
tests/data/melodymodel/5_2/Melody Model Test.capella
tests/data/pvmt/expected-output/apply.melodymodeller
tests/test_model_layers.py
tests/test_pvmt.py

It was discovered that our test models somehow had gotten multiple elements that shared the same UUID. While investigating the cause of this, I implemented this simple routine that checks for such duplication while loading and before saving a model. As a side effect of where the code is hooked into, this also adds an additional guard while creating / inserting new elements into the model's XML tree.
The PVMT tests needed to be adjusted, because a mock function would always return the same UUID, which triggered the new before-save check.

Detect UUID duplication within models

---

capellambse/model/__init__.py

Accept FileHandler instance or a dictionary with its parameters as input
for the `diagram_cache` argument of the MelodyModel class.
Co-authored-by: Martin Lehmann <martin.lehmann@deutschebahn.com>

feat: Extend types for `diagram_cache` parameter

---

tests/test_reqif.py

We never made guarantees about the order of the elements returned from
`model.search()`, but until e79a63a71a7ceae1e466331985cd056bfb3efdc8
they at least used to be stable between invocations. This is no longer
the case, which broke a test that relied on it.

test(reqif): Fix spurious test failure

---

pyproject.toml
tests/__init__.py
tests/conftest.py
tests/test_model_layers.py
tests/test_model_loading.py

In a recent team meeting, we agreed to migrate to this option. Here goes capellambse.

test: Refactor for pytest's `--import-mode=importlib`

---

capellambse/svg/style.py

Writing Circle styles is provided by the edge style-writer already.
Please get this merged in as fast as possible as [PR #9](https://github.com/DSD-DBS/capellambse-context-diagrams/pull/9) depends on it.

fix: Diagrams with default Circle styling

---

README.rst

The status badges in the README are displayed in new lines... this can be fixed by adding `:target:`s as described in [this issue](https://github.com/badges/shields/issues/1491).

Fix side by side badges in README

---

capellambse/extensions/reqif/elements.py

Fix a bug where creation of `AttributeDefinitionEnumeration`s and saving them would make Capella not show any layers anymore.

Fix wrong `_xmltag` for `AttributeDefinitionEnumeration`

---

capellambse/extensions/pvmt.py
capellambse/model/layers/la.py
capellambse/model/layers/pa.py

27e998634db1d424270720945b179c94a3894ab2 and other, even earlier commits broke references to `.functions` attributes (both in code as well as docstrings). This commit fixes those references by updating them to their correct names.

fix: Fix broken references to `.functions`

---

capellambse/loader/core.py
capellambse/loader/filehandler/__init__.py
capellambse/model/__init__.py

If the `MelodyModel` was initialzed from a remote URL and the user intents to use `.save(push=True)` (i.e. `write_transaction` is executed) an up2date cache is needed. This is ensured by the default `update_cache=True` parameter. I felt the urge to update the docs with additional notes about this dependence at the right places.
Take notice that I used a `~` in `:class:`~capellambse.loader.filehandler.FileHandler`` to shorten the rendered reference to only `FileHandler`.

Add a note for save and update_cache dependance

---

.gitattributes
.pre-commit-config.yaml
capellambse/decl.py
capellambse/model/common/accessors.py
capellambse/model/common/element.py
capellambse/model/crosslayer/cs.py
capellambse/model/crosslayer/fa.py
capellambse/model/layers/la.py
capellambse/model/layers/oa.py
capellambse/model/layers/pa.py
docs/source/index.rst
docs/source/start/declarative.rst
examples/10 Declarative Modeling.ipynb
examples/10 Declarative Modeling.ipynb.license
pyproject.toml
tests/data/decl/coffee-machine.yml
tests/data/decl/empty_project_52/.project
tests/data/decl/empty_project_52/.project.license
tests/data/decl/empty_project_52/empty_project_52.afm
tests/data/decl/empty_project_52/empty_project_52.afm.license
tests/data/decl/empty_project_52/empty_project_52.aird
tests/data/decl/empty_project_52/empty_project_52.aird.license
tests/data/decl/empty_project_52/empty_project_52.capella
tests/data/decl/empty_project_52/empty_project_52.capella.license
tests/test_decl.py
tests/test_reqif.py

This PR introduces a modelling language based on a YAML format. Please refer to the added documentation for details.
Mandatory main goals for this PR:
Optional goals, which may also be moved to a separate, later PR:

YAML-based declarative modelling

---

capellambse/aird/capstyle.py
capellambse/aird/parser/_edge_factories.py
capellambse/aird/parser/_filters/global.py
capellambse/svg/drawing.py
capellambse/svg/symbols.py

This PR improves the rendering of class diagrams (i.e. diagrams with class type **[CDB]**) provided by the svg submodule.
The following happened:
- Added 2 new filters:
- `hide.role.names.filter`
- `hide.association.labels.filter`
- The Association edge factory was fixed. There was a bug that caused wrong labels (only navigable role names) to appear in the SVG. The factory now does only patch the style class from the `aggregationKind` attribute of the first melodyobject. From this syleclass (Association (per default), Aggregation and Composition) we infer which end-marker is to be taken and added to the defs section of the drawing.
- The `FilledDiamondMarker` for the `Aggregation` styleclass was added to decorations.
The bugs around bendpoints calculation causing unorthogonal routing …

Fix class diagrams ([CDB])

---

capellambse/model/layers/oa.py

In order to standardize the `.related_exchanges` attribute I propose to rename the `exchanges` property of `OperationalActivity` to `related_exchanges`. This makes my life easier in the context diagrams collection stage.

Rename the `exchanges` attribute to `related_exchanges` on OperationalActivity

---

capellambse/loader/core.py
tests/test_model_loading.py

Valid entrypoint file-types are `.aird` and `.airdfragment` coming from `VISUAL_EXT`. This solves #159.
Another solution would be to not raise an `InvalidEntrypoint` exception but rather look for valid entrypoints in the same directory of the given entrypoint. Assuming that modelfiles are kept together in the same directory. But this doesn't incentivise to pass the correct entrypoint which is the `.aird`/`.airdfragment` file.

Disallow model loading from capella files without valid entrypoint

---

capellambse/model/crosslayer/information/__init__.py
tests/data/melodymodel/5_2/Melody Model Test.capella

This PR solves #195 and comes with `realized_classes`, `realizations` (giving access to the new `InformationRealization` object) and `realized_by` attribute for reversed access.

Add `realization` attributes to `Class`es

---

capellambse/extensions/reqif/elements.py

Relations tried to display the full `repr()` of their source and target, which is not only unnecessarily verbose, but also caused a recursion error. Use the `_short_repr_()` of source and target instead.

Fix repr of relations

---

capellambse/extensions/reqif/elements.py
tests/data/melodymodel/5_2/Melody Model Test.capella
tests/test_reqif.py

The title says it all. Pay attention to the added test that is testing the `_short_repr_` appearances in the `__repr__` of certain ReqIFElements instead of testing successful execution via `xtype`.

Simplify `_short_repr_` of `ReqIFElement`s and `Relations`

---

README.rst
capellambse/loader/core.py
capellambse/model/__init__.py
capellambse/model/common/element.py
docs/source/conf.py
docs/source/development/low-level-api.rst
docs/source/index.rst

This PR adds documentation for the low-level API. In doing so, it also improves on related preexisting docstrings in the `capellambse.loader` package, and adds a few minor convenience improvements to the API.
Resolves #201.

Documentation for the low-level API

---

capellambse/decl.py
capellambse/model/common/accessors.py
capellambse/model/crosslayer/cs.py
tests/test_xlayer_cs.py

This PR enables context collection for `PhysicalComponent`s in the [context-diagrams-extension](https://github.com/DSD-DBS/capellambse-context-diagrams/pull/23).

Fix physical links

---

capellambse/diagram/__init__.py
capellambse/diagram/_styleclass.py
capellambse/model/crosslayer/capellacommon.py
capellambse/model/crosslayer/fa.py
capellambse/model/crosslayer/information/__init__.py
capellambse/model/crosslayer/modellingcore.py
capellambse/model/layers/oa.py
capellambse/model/modeltypes.py
tests/test_model_layers.py

This PR publishes the new `get_styleclass` function which is used in DSD-DBS/capellambse-context-diagrams#27. With this function the user can receive the necessary styleclass string used for styling objects in a diagram representation.

Add high level `get_styleclass` function

---

capellambse/cli_helpers.py
capellambse/model/diagram.py
pyproject.toml

This PR enables printing diagrams straight to a terminal that supports it. (Currently we only recognize [kitty](https://sw.kovidgoyal.net/kitty/) as supporting it. In the future, we might want to look at libraries that implement proper auto-detection.)
This also works with third-party plugins that add new types of diagrams, as long as they inherit from the `AbstractDiagram` class (and don't override `__repr__`). The context-diagram extension was tested and is confirmed working without any modifications.
Here's a screenshot of the feature in action, using the `capellambse.repl` shell:

Terminal improvements (and graphics)

---

.gitignore
CONTRIBUTING.rst
capellambse/extensions/metrics/__init__.py
capellambse/extensions/metrics/collector.py
capellambse/extensions/metrics/composer.py
capellambse/model/__init__.py
docs/source/examples/11 Complexity Assessment.ipynb
docs/source/examples/11 Complexity Assessment.ipynb.license

This adds a basic summary badge property to a model. 
in response to `model.description_badge` we get an SVG string that provides a visual summary of model composition and key object counts across the engineering layers. 
I wonder if we could also make this a default `display` behavior for the model object itself, since this function call doesnt seem to cost much in terms of resources.

Model description (complexity) badge

---

capellambse/extensions/reqif/_capellareq.py
capellambse/model/common/accessors.py
capellambse/pvmt/types.py
tests/test_auditing.py
tests/test_reqif.py

This PR fixes some minor bugs that must have happened during the merge of the requirements into the change-auditing branch.
Somehow the passed element in an `capellambse.delete` audit event wasn't the parent object (as it is documented) but the deleted object itself. Additionally `_operate_modify` would fire an `AttributeError` b/c an `__delete__` was missing on the `AttrProxyAccessor` which is needed for setting a new values-list on an `EnumerationValueAttribute`.

Fix minor bugs from change audit and requirements merge

---

capellambse/loader/core.py
capellambse/loader/exs.py
capellambse/loader/modelinfo.py
capellambse/model/__init__.py
capellambse/model/common/element.py
tests/data/writemodel/WriteTestModel.afm
tests/data/writemodel/WriteTestModel.aird
tests/data/writemodel/WriteTestModel.capella
tests/test_model_creation_deletion.py
tests/test_model_loading.py

In order for the types of model elements to be correctly identifiable, the namespace has to be defined on the fragment's respective root element. This commit adds new methods for this purpose, and ensures that `GenericElement.__init__` calls them with the correct values.

Add namespaces when creating elements

---

capellambse/filehandler/gitlab_artifacts.py
capellambse/model/__init__.py
pyproject.toml

This file handler uses the Gitlab API to request files from the "artifacts" archive of a recent successful CI job.

Add a Gitlab artifact file handler

---

capellambse/extensions/reqif/_capellareq.py
capellambse/loader/core.py
capellambse/model/common/accessors.py
docs/source/start/audit-events.rst
tests/test_auditing.py
tests/test_model_creation_deletion.py

This PR introduces a new function `MelodyModel.find_references(target)`, which enumerates all existing model objects that contain a reference to the given target object. This function is used while deleting objects to ensure that no dangling references are left behind. Dangling references break the model by causing exceptions (in capellambse) and preventing the removal of affected objects (in Capella).
Resolves #256.

Delete dangling references to deleted model objects

---

ci-templates/gitlab/README.rst
ci-templates/gitlab/filter-derive.yml
ci-templates/gitlab/model-badge.yml

This PR modifies the Gitlab CI template of the filtering CLI feature. While it was previously deriving the projects and just storing them in a Gitlab artefacts, this change introduces a new option to push the derived projects to individual branches.
This opens a new range of possibilities and more flexibility. Users can define custom Gitlab CI pipelines for each branch / derived project. As this also includes the diagram cache, the previously added diagram cache job for derived models has been removed.
Please note: This is a breaking change. Given that the [filtering CLI](https://github.com/DSD-DBS/py-capellambse/pull/266) PR has only been merged recently, I don't expect a broad usage of the existing Gitlab CI template.

Filtering Gitlab CI template: Push derived models into different branches

---

capellambse/model/__init__.py
capellambse/model/common/__init__.py
capellambse/model/common/element.py

Previously:
```python
>>> model
<capellambse.model.MelodyModel object at 0x7f627f6d1770>
>>> model.la.parent.parent
<Model element (org.polarsys.capella.core.data.capellamodeller:Project) 'Melody Model Test' (af2196ac-49d3-4063-885c-9fa29adc39a8)>
[...]
```
Now:
```python
>>> model
<capellambse.model.MelodyModel object at 0x7f627f6d1770>
>>> model.la.parent.parent
<capellambse.model.MelodyModel object at 0x7f627f6d1770>
```

Fix access to MelodyModel through `.parent` chain

---

capellambse/loader/core.py

This pull request refactors the `add_namespace` method in the loader module to improve namespace handling. Specifically, it modifies the behavior of the method to log a warning instead of raising an error when an already registered URI is detected. This change enables users to apply a declarative YAML to a Capella 6.0.0 model, which was previously not possible due to the strict error handling in this method. With this change, the URI for a given namespace can be updated if necessary, without causing an error to be raised. Overall, this improves the robustness and usability of the code.

Show namespace warning instead of error on mismatch

---

ci-templates/gitlab/filter-derive.yml

This fixes a weird issue that manifested in one of our pipelines. The Gitlab runner had a stale branch pointer still lying around from ... somewhere, which had fallen behind the upstream branch tip; this caused the push to be rejected because it was non fast-forward.
This PR fixes the issue by specifically fetching all "derived/*" branches directly into the local branches namespace. This ensures that we have up-to-date branch pointers for all branches that are already known upstream.

Ensure "derived" branch pointers are up to date

---

capellambse/_diagram_cache.py

The previous attempt at sanitizing SVGs (cac71b80045f2ab08605c843592d3f53eb393dbf) was incomplete and caused rendering issues in other places, where some black lines and boxes were not being properly drawn. Instead of blanket patching out the default black fill and stroke properties from the tree root, this new fix only alters them on `<clipPath>` elements.

Fix SVG sanitization in diagram cache

---

capellambse/model/__init__.py
capellambse/model/diagram.py
tests/test_model_loading.py

Experience has shown that it's more often than not undesirable to have the internal rendering engine jump in for diagrams that could not be found in the cache. This commit arranges for the internal engine to be disabled for AIRD diagrams by default if a cache was specified. This behavior can be overridden by setting the new ``fallback_render_aird`` model load parameter to ``True``, which re-enables the rendering engine for all diagram types.
Diagrams that do not come from one of the model's AIRD files are not affected, and will always fall back to the internal engine. This means that e.g. context-diagrams, which are generated on-the-fly, will continue to work as expected, without the need to pre-generate them.
Resolves #287.

Disable AIRD renderer if diagram_cache was given

---

capellambse/_diagram_cache.py
capellambse/diagram_cache.py

This PR makes some improvements to the built-in diagram caching functionality:
- The generated `index.json` now contains new `viewpoint` and `type` keys for each diagram.
- The `index.html` was restyled. Diagrams are now grouped by viewpoint and prefixed with the diagram type.
- The CLI will try to use executables named like `capella5.2.0` or `capella6.0.0` by default if no means of running native Capella was specified.
The added keys in the JSON index might be interesting for the [DSD-DBS/capella-collab-manager](https://github.com/DSD-DBS/capella-collab-manager) team, and could be a nice addition to display somewhere (and allow filtering for) in the diagram UI. @MoritzWeber0 what are your thoughts? Do you think you can work with this? Particularly, would it make more sense to have the …

Diagram cache CLI usability improvements

---

capellambse/filehandler/memory.py
tests/test_filehandler_memory.py

This file handler stores all data in `bytearray` instances in memory. It's going to be used for tests later down the line.

Add an in-memory file handler

---

capellambse/aird/__init__.py
capellambse/model/diagram.py
tests/test_aird_parser.py

This commit adds `yield_diagram_elements` which is then used in the `nodes` property of `AbstractDiagram`. This function doesn't build the whole diagram and all elements as aird objects (Box, Edge, ...). Instead it just collects the targets and finds the referenced semantic elements. This saves a lot of time when requesting `nodes`.

Make `diagram.nodes` faster

---

capellambse/filehandler/git.py
tests/test_model_loading.py

For local git repos, the locking mechanism would put the `capellambse.lock` file into the root of the worktree. This was annoying, as that file had to be explicitly gitignore'd or it would show up in diffs and `git status`.
This commit changes `self.__repo` to point to the $GITDIR instead of the main worktree root, thereby moving the lockfile there. This more closely mirrors the behavior of remote git repos, which don't have a main worktree and therefore also have `__repo` point to the $GITDIR.

Move lockfile into $GITDIR

---

capellambse/extensions/metrics/composer.py

This PR adds a newline at the end of the model badge svg. 
(Helping e.g. to not have failing pre-commit hooks that are checking for a last empty line in files or to have a new line when printing in the console)

Add newline to model badge svg

---

pyproject.toml

This matches the config we agreed on in our cookiecutter.

Configure `coverage.py`

---

capellambse/model/common/element.py

In the `__html__` representation, which is used for Jupyter, the name of the type of the element was displayed.
While the type is relatively uninteresting for the user, especially because the xtype is displayed right after it, the name of the element itself was missing completely in the representation.
This commit replaces the type name with the element if a element name is available.
State before this commit: 
State after this commit:

Display name of element in `__html__` heading

---

capellambse/model/diagram.py
pyproject.toml
tests/test_svg.py

JupyterLab (unlike the legacy "Jupyter notebook server") prefers JSON over SVG for display purposes. Capellambse used to expose its internally used JSON format in the diagrams' `_repr_mimebundle_()` method. This caused JupyterLab to not show diagrams properly when using `display()` or when a Diagram instance was the result of a cell.
Furthermore, the way that the `_repr_mimebundle_()` method returned its `application/json` mimetype (encoded as a string, instead of as regular Python dict) was never supported to begin with.
This PR fixes both of these issues by no longer exposing this internal format publicly. This means that:
- `_repr_mimebundle_()` will no longer contain `application/json`
- `AbstractDiagram.render()` will no longer accept `json` and `json_pretty` as format argument
- The …

Fix diagram rich display in JupyterLab

---

capellambse/_native.py

When Capella errors, it creates a dialog on the display. The Capella process is blocking until the user clicks "Close" in the GUI, which will never happen in a CI/CD environment.
To suppress errors in the GUI, the `--launcher.suppressErrors` is passed to Capella/Eclipse. As positive side-effect, the errors are now also printed in stderr and are therefore handled by capellambse.

fix: Don't block Capella on error in native client

---

capellambse/_diagram_cache.py
capellambse/diagram_cache.py
capellambse/model/__init__.py

This PR adds the option to add white background to the diagram cache via the cli
Example in green to show the extend of the background and that it is only around the diagram

feat: Add white background if needed to diagram cache svg

---

capellambse/svg/drawing.py

Labels for ports (FIP/FOP etc.) usually don't have their own style class associated with them, which means they should simply be drawn with default black text. This commit changes the label drawing function to not expect a class to be set for the label text.
Fixes #325

Fix crash in SVG renderer when drawing port labels

---

ci-templates/gitlab/model-badge.yml

The push can be disabled by setting the new environment variable `CAPELLAMBSE_PUSH_MODEL_BADGE` to 0. The default is the current behavior, i.e. to push the badge (1).

Make pushing the complexity badge optional in Gitlab

---

capellambse/extensions/reqif/_capellareq.py
tests/test_reqif.py

This is needed to bring our RequirementsBot into working state again. 
While fixing the creation of `Relation`s from the `reqif.Requirement` side, what about the other side? So creating `CapellaOutgoingRelation`s from any model object to a `reqif.Requirement` can't be done via capellambse right now, or? I can't find a `.relation` attribute on `GenericElement`. Also there are 2 ways of creating `Relation`. Both lead to different places of where the `Relation` XML element is written to: Either underneath the model object or underneath the Requirement. The GUI accepts both, so I'd root for capellambse creating `Relation`s just underneath the `reqif.Requirement` to keep the reqif content compact and bundled inside the `RequirementsModule`. The latter hasn't been done for now, and is the main …

Fix creation of `Relation`s from a `Requirement`

---

capellambse/_diagram_cache.py
capellambse/diagram_cache.py
capellambse/model/__init__.py

- Expose the `IndexEntry` typed dictionary to the public.
- Update the docstring to include descriptions for `type` and `viewpoint` attributes on `IndexEntry`.

Fix-diagram-cache

---

capellambse/diagram/_styleclass.py
capellambse/diagram/capstyle.py
capellambse/svg/symbols.py

Styleclasses for `information.Property`s couldn't be resolved based on the `kind` attribute. Also end-markers were missing for composition and aggregation kinds of properties in a CDB diagram. The ref x coordinate for the FineArrowMarker was corrected to be exact centric.
**_These changes are needed in the Class-Tree feature for the [capellambse-context-diagrams #53](https://github.com/DSD-DBS/capellambse-context-diagrams/pull/53) extension._**

Fix Property class

---

capellambse/filehandler/http.py
tests/test_model_loading.py

This PR adds a few new percent-escapes, which allow for more fine-grained control over how the image path is passed to the backend server.

Add more percent-escapes to the HTTPFileHandler

---

capellambse/aird/__init__.py
capellambse/extensions/metrics/composer.py
tests/test_aird_parser.py

Just because nobody bothered to draw pretty pictures, doesn't make the whole XML invalid. Apparently diagram-less models are a thing after all.

Don't crash if there are no diagrams in the model

---

capellambse/svg/drawing.py
capellambse/svg/helpers.py

The feature text span x coordinate was always calculated for a centric rendering. This commit fixes it by opening the door

Fix feature text alignment

---

capellambse/model/layers/pa.py
capellambse/model/modeltypes.py
tests/test_model_layers.py

Somehow `.nature` could return a `None` value. It should default to
`Node`.

Fix definitions of PhysicalComponent nature and kind

---

capellambse/_diagram_cache.py
capellambse/diagram_cache.py

This PR adds a new flag to the `capellambse.diagram_cache` CLI, which allows to "refresh" all diagrams (i.e. synchronize them with the actual model contents) before exporting them (see aa44b4ce2dbfa328cdb5df9993d95f390b4e8272 - the other two commits merely refactor the surrounding code a little bit).
Open questions:

Optionally refresh diagrams before exporting them to the cache

---

capellambse/model/common/element.py

When determining which type of indexing is requested for an ElementList (slice, mapping-like or list-like), treat str indices (i.e. mapping-like) as the special case and integer indices as the regular case. This improves compatibility with libraries that provide their own specialized integer classes, which are not subclasses of Python's standard `int`, such as numpy's fixed-size int8/16/32/64.

Treat str indices to ElementList as the special case

---

capellambse/aird/_common.py
capellambse/diagram/_diagram.py
capellambse/diagram/capstyle.py
capellambse/model/common/__init__.py
capellambse/model/common/element.py
capellambse/svg/decorations.py
capellambse/svg/drawing.py
capellambse/svg/generate.py
capellambse/svg/symbols.py
tests/test_svg.py

Some fixes for decoration and styling of diagrams.

Fix-decorations

---

capellambse/helpers.py
capellambse/model/diagram.py

Once this is released, we should also update the example snippets in the context-diagrams docs, where the svgdiagram based approach is used quite extensively.

Diagram pretty-printing and saving

---

capellambse/aird/_edge_factories.py
capellambse/aird/_semantic.py
capellambse/diagram/_styleclass.py
capellambse/diagram/capstyle.py

The `FunctionalExchange`s in OA diagrams are not styled correctly. This is caused by a faulty/missing styleclass factory and aird factory patching the style class to `OperationalExchange`.
Additionally missing default styles were added.

Use correct FunctionalExchange styleclass on OA

---

capellambse/aird/_styling.py
capellambse/diagram/_diagram.py
capellambse/diagram/_json_enc.py
capellambse/diagram/capstyle.py
capellambse/svg/drawing.py
capellambse/svg/style.py
capellambse/svg/symbols.py
tests/test_svg.py

This commit fixes too large rendered text in PDF rendered with
weasyprint. Therefore the following is done:
- Change pt to px since this is used in underlying text measuring
function.
- Simplify icon positioning. This fixes uneven distances between icon
and text.
Example diagram SVG with the changes to the engine:

Fix SVG rendering

---

.github/workflows/docs.yml
docs/Makefile
pyproject.toml

This should help find issues with the documentation early, before it lands on master and has a chance to accumulate.

Treat Sphinx warnings as errors

---

.pre-commit-config.yaml

Older pre-commit versions are not compatible with the used pre-commit configuration since the `commit` stage was renamed to `pre-commit`.
This can lead to error messages like:
> Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, post-rewrite, prepare-commit-msg, push but got: 'pre-commit'
With a minimum required version the error messages is clearer.

ci: Enforce `pre-commit` version >= 3.2.0

---

capellambse/model/__init__.py
ci-templates/gitlab/filter-derive.yml

The `capella/cli` image in the [capella-dockerimages repository](https://github.com/DSD-DBS/capella-dockerimages) was deprecated in https://github.com/DSD-DBS/capella-dockerimages/pull/152. More information is available in the release notes: https://github.com/DSD-DBS/capella-dockerimages/releases/tag/v1.12.2.
While the old image is still functual, it is no longer built and therefore doesn't receive any new updates.
The `capella/cli` image was replaced with the `capella/base`. The interface is the same.
In addition, I changed one example in the documentation to point to the prebuilt Capella image from the capella-dockerimages repository.

fix: Replace references to deprecated `capella/cli` image

---

capellambse/_diagram_cache.py
capellambse/_native.py
capellambse/extensions/filtering.py
capellambse/loader/core.py

The 'write_tmp_project_dir' method is now able to create a full workspace structure when more than one resource is involved in a model. Previously, calling this method on a model with loaded resources (i.e. library models) would result in an exception.

Handle resources in write_tmp_project_dir

---

capellambse/decl.py
capellambse/model/common/__init__.py
capellambse/model/common/accessors.py
capellambse/model/crosslayer/information/__init__.py
capellambse/svg/drawing.py
capellambse/svg/symbols.py
docs/source/start/declarative.rst
tests/conftest.py
tests/data/melodymodel/5_0/Melody Model Test.aird
tests/data/melodymodel/5_0/Melody Model Test.capella
tests/data/melodymodel/5_2/Melody Model Test.aird
tests/data/melodymodel/5_2/Melody Model Test.capella
tests/data/melodymodel/6_0/Melody Model Test.aird
tests/data/melodymodel/6_0/Melody Model Test.capella
tests/test_decl.py

This aims at making it easier to implement synchronization between a Capella model and other sources of information. With the currently possible operations (create/extend, modify and delete), a lot of manual logic is necessary to find objects that already exist and need to be updated with new content. `sync` aims to abstract that logic out into the common denominator that is `decl` itself.

Implement a "sync" operation for declarative YAML

---

capellambse/decl.py
docs/source/start/declarative.rst

~~sync set should be called sync modify~~ modify should be called set. it's weird that it has to be:
```
- parent: !uuid blahblah
modify:
description: "hey"
```
for parent, but for find it's:
```
- find:
name: blah
set:
description: "hey"
```
even though they both do the same thing.
it should instead be:
```
- parent: !uuid blahblah
set:
description: "hey"
```

Declarative: Rename modify to set

---

tests/data/melodymodel/6_0/.project

All test projects must at least list the Capella project nature to serve as Capella test project. If this nature is missing, it is just a general (generic) Eclipse project.
This is especially of relevance, when using the Java API of Capella since many basic Capella API calls cannot be used. The nature is also needed to work with the Capella perspective in Eclipse.

Add missing Capella nature in test project

---

capellambse/diagram/_diagram.py

Text transforms are used for translations and rotations. Right now we only use rotations, such that positions can be very large since they are transformed anyways. I propose to trust the user with the calculated points instead of checking them during our calculations.
**_This is needed to fix unnecessary whitespace in realization view diagrams in the [context-diagrams extension #90](https://github.com/DSD-DBS/capellambse-context-diagrams/pull/90)._**

Ignore labels with transforms from bounds calculation

---

capellambse/_native.py

When invoking a native Capella installation via Docker, `capellambse` did always pull the image from a remote environment.
This has two disadvantages:
- It's not possible to work with local images which don't exist in a remote registry.
- It's vulnarable to dependency confusion since attackers could upload a vulnarable Docker image with the same name as the local image to DockerHub.
The new behviour is:
`capellambse` checks if the image exists locally.
If it exists, continue with the local image. Otherwise, pull it from the remote.
This also matches the behaviour when using the `docker run` CLI.

Prefer local over remote Docker images

---

.pre-commit-config.yaml
capellambse/extensions/validation/__init__.py
capellambse/extensions/validation/__main__.py
capellambse/extensions/validation/_validate.py
capellambse/extensions/validation/report-template.html.jinja
capellambse/extensions/validation/rules.py
capellambse/model/common/__init__.py
capellambse/model/layers/la.py
pyproject.toml
tests/test_validation.py

Based on the modeling rules maintained in our internal Polarion and the old PR #270 that outlined the work for me, I have implemented the modeling rules in py-capellambse.
To generate the metrics report, run the following command:
python -m capellambse.extensions.validation -m [model] -o report.html
This command will create a report.html file containing all the applied modeling rules and the metrics report.

Modeling rules and validation

---

capellambse/model/crosslayer/cs.py

There can be multiple `exchange_item_allocations` as the name suggests.

fix(model): Fix `Interface` `exchange_item_allocations`

---

.github/workflows/docs.yml

Use `-W` to Sphinx only when building on pull requests, but not master. This allows to easily catch new warnings during PRs, while still allowing to ignore them for a while and keep up to date documentation built for master in most cases.

Ignore Sphinx errors on master builds

---

.github/workflows/code-qa.yml
pyproject.toml

The pipeline on master is unsuccessful because only non-dev versions can be uploaded to PyPI. This fixes the situation by only triggering the pypi stage when a release tag was created.

ci: Only trigger pypi push on release tag

---

capellambse/_diagram_cache.py
capellambse/diagram/_icons.py
capellambse/helpers.py
capellambse/svg/decorations.py
capellambse/svg/drawing.py
capellambse/svg/helpers.py
tests/test_svg.py

- Adjust font size and line height to closer match Capella diagrams
- Improvements to line wrapping
- Fix label positioning bug where childless boxes didn't have their labels centered for a while now
- ~~Added NotFoundSymbol for unknown/custom icons~~
- Improvements to FunctionSymbol to closer match Capella's FunctionSymbol
Fixes #442

Improve rendering for xAB diagrams

---

capellambse/model/_descriptors.py
tests/test_metamodel_cs.py
tests/test_model_layers.py

Fix the bugs in DeepProxyAccessor and RoleTagAccessor, discussed in #446.

Fix Deep and RoleTag accessor behavior

---

capellambse/aird/_edge_factories.py
capellambse/diagram/_icons.py
capellambse/svg/drawing.py

Partially solves #78
solved:
- Added class property, enum and enum literal icons
- Added multiplicity to class diagram edges
not solved:
- didn't add icons for Box.NumericType and Box.StringType because why would you need that
- aggregation kind of associations still don't have the Diamond-Marker when kind attribute isn't in the XML. not possible to implement atp

fix: Add icons and multiplicity to class diagrams

---

capellambse/metamodel/capellacommon.py
tests/test_metamodel_common.py

Hello py-capellambse team, and thank you very much for this great project and especially for the amazing contributor experience!
I'm interested in working with `StateMachine`s and the relations within and around them, so I noticed #426 which I'll now stop spamming with mentions. To start from the related `StateTransition`s, this PR adds:
- `incoming_transitions`
- `outgoing_transitions`
Please check the commits for the detailed lists of classes impacted, which can also be rolled back to just `State`.
The PR also adds test cases for both of these new accessors on `State`, and for `InitialPseudoState.outgoing_transitions`; I couldn't find a `StateMachine` with a `FinalState` to write the test case for `FinalState.incoming_transitions` but it should be easy to add with the right UUIDs. …

Enhance *State/Mode classes with incoming and outgoing StateTransition accessors

---

.pre-commit-config.yaml
capellambse/decl.py
docs/source/start/declarative.rst
pyproject.toml
tests/test_decl.py

The declarative modelling YAML needs a metadata section in order to ensure successful application of it that leads to a healthy model. With [RM Bridge issue #39](https://github.com/DSD-DBS/capella-rm-bridge/issues/39) and a following PR this will be implemented.
This PR anticipates these changes and implements metadata checks during `decl.apply()` against the `model.info`. These checks can be found [here](https://github.com/DSD-DBS/py-capellambse/blob/decl-metadata/capellambse/decl.py#L191-L220) and are [tested](https://github.com/DSD-DBS/py-capellambse/blob/decl-metadata/tests/test_decl.py#L550-L628).

Add an optional metadata section to declarative modelling

---

capellambse/diagram/capstyle.py

Apparantly `PhysicalLink` and `PP` (PhysicalPorts) can exist in the System Analysis and Logical Architecture Layer. But there is no styling in the registry in capstyle.py yet. This commit fixes it.

Move PhysicalLink and -Port styles to `__GLOBAL__`

---

capellambse/loader/core.py

When encountering a file with an unknown file name extension, we used to simply crash the program. Instead, we now still try to load the model, but print a warning about potentially missing content. This enables limited use of capellambse on models that use external extension data, such as the `*.traceability` files created by the Publication for Capella extension.
Note that even when simply loading such a model will succeed, some runtime data access may cause errors due to the missing extension data. To avoid creating bigger problems down the line, capellambse will refuse to save such a model without also passing the extra save() flag `i_have_a_recent_backup=True`, similar to the behavior when ignoring UUID duplication.

Ignore unknown file types when loading a model

---

capellambse/extensions/filtering.py
capellambse/extensions/pvmt/_config.py
capellambse/extensions/reqif/_capellareq.py
capellambse/extensions/reqif/_requirements.py
capellambse/metamodel/__init__.py
capellambse/metamodel/capellacommon.py
capellambse/metamodel/capellacore.py
capellambse/metamodel/capellamodeller.py
capellambse/metamodel/cs.py
capellambse/metamodel/fa.py
capellambse/metamodel/information/__init__.py
capellambse/metamodel/information/datatype.py
capellambse/metamodel/information/datavalue.py
capellambse/metamodel/interaction.py
capellambse/metamodel/la.py
capellambse/metamodel/modellingcore.py
capellambse/metamodel/oa.py
capellambse/metamodel/pa.py
capellambse/metamodel/sa.py
capellambse/model/__init__.py
capellambse/model/_descriptors.py
capellambse/model/_model.py
capellambse/model/_obj.py
tests/test_model_creation_deletion.py

This commit performs the following renames:
- RoleTagAccessor to Containment
- AttrProxyAccessor to Association
- LinkAccessor to Allocation
- ReferenceSearchingAccessor to Backref
The old names of these Accessors will still be available at runtime until the end of v0.6.x.

Rename basic Accessors to make their roles clearer

---

capellambse/loader/core.py
docs/source/start/envvars.rst
tests/data/pvmt/expected-output/apply.capella
tests/test_model_pvmt.py

This commit changes the UUID generation logic to use its own `random.Random` object, which may be seeded using the newly introduced `CAPELLAMBSE_UUID_SEED` environment variable. This may be used to create reproducible results across multiple runs of an automation.
This also changes the PVMT tests to patch the used Random generator with a static seed instead of overriding the `generate_uuid` method, which greatly simplifies the test setup code.
***Stacked on #485***

Add an envvar to generate deterministic UUIDs

---

.github/workflows/code-qa.yml

This is especially useful when stacking PRs and pushing an entire stack at once, because each stacked PR will trigger multiple times per push (at least once each for the pushed base and head branch, possibly even more for larger stacks, depending on the processing order).

Cancel old Code QA workflows on new pushes

---

src/capellambse/_diagram_cache.py

Do not consider the XML declaration as a potential graphical element for which the bounding box should be calculated.

Make SVG viewbox cropping more resilient

---

src/capellambse/_diagram_cache.py
src/capellambse/diagram_cache.py

Signal to the caller that some diagrams failed to export by exiting with code 3. This allows automated scripts to more easily distinguish this case from other errors.

Exit 3 on partial diagram cache export failure

---

src/capellambse/cli_helpers.py

See also 0b4ca00d0cdc91c1267d4bd7aea3f5d20707ce16.
This keeps the returned modelinfo dict to simple basic types, which makes analyzing and logging easier downstream.

Defer loading the filehandler until after `loadinfo`

---

src/capellambse/_diagram_cache.py
src/capellambse/model/_model.py
src/capellambse/model/diagram.py

- Add the export format to the index entries
- Use the index for reducing cache lookups if it exists

Improve the diagram cache index

---

src/capellambse/diagram/_icons.py

Finally get rid of the too little space inbetween the icon and label of `SystemComponent` and `SystemActor`.

Improve spacing for SystemComponent / -Actor symbols

---

src/capellambse/decl.py

The description text is never actually needed in a production environment, and only exists for convenience during debugging. Evaluate it lazily via a `__str__` method instead of passing already rendered text into the constructor.
This slightly improves performance by avoiding unneeded work, and more importantly, it avoids an accidental dependence on the 'termgraphics' converter (read: PNG support) when connected to a compatible TTY while applying decl YAML.

Evaluate `_NoObjectFoundError` description lazily

---

.github/workflows/code-qa.yml
pyproject.toml

In this commit the publish to PyPI job is outsourced into its own workflow such that it is only executed when a new release tag is created. Since the publish job depends on build jobs which were only defined in the code-qa workflow, a reusable workflow was defined.
See the [docs](https://resources.github.com/learn/pathways/automation/intermediate/create-reusable-workflows-in-github-actions/) for reusable workflows.

Fix the publishing workflow

---

pyproject.toml
src/capellambse/filehandler/git.py

Fix unraisable exception during Git worktree cleanup on Windows

---

src/capellambse/model/_model.py
src/capellambse/model/diagram.py

Previously, passing `fallback_render_aird` would only cause a fallback to the internal rendering engine on cache misses. With this commit, diagrams are also rendered internally for any other cache error, for example if a remote cache server is unreachable or the cached artifacts have expired.

Allow falling back to internal rendering on any cache error

---

ci-templates/gitlab/filter-derive.yml
ci-templates/gitlab/model-badge.yml

The fetch depth is sufficient and speeds up the pipelines.

perf: Reduce fetch depth to 1 in Gitlab pipelines

---

src/capellambse/metamodel/capellacore.py
src/capellambse/model/_obj.py

This allows access like:
```python
some_pv_group["Property"] = 7
```
It's especially convenient in combination with PVMT.
This behavior was already documented, and I'm pretty sure it was also implemented at some point, so I'm marking this as a "fix".

Reimplement the dict-like interface for PropertyValueGroup

---

src/capellambse/metamodel/cs.py

Allow the properties to return None, like source and target on other Exchange-type classes. This enables more graceful handling of models where the PhysicalLink does not have two 'ends' defined.

Make ``PhysicalLink.{source,target}`` more resilient

---

src/capellambse/metamodel/cs.py
src/capellambse/metamodel/pa/__init__.py
tests/test_metamodel_cs.py

This PR implements the `cs.Part` creation of at least one part when creating a new Component. The name of the Part is now correctly inferred from its type.

Automatically create a Part for new Components
