dbinfrago/py-capellambse

capellambse/model/crosslayer/fa.py
docs/capella-python-api/capella-python-api.aird
docs/capella-python-api/capella-python-api.capella
tests/data/melodymodel/5_0/MelodyModelTest.afm
tests/data/melodymodel/5_0/MelodyModelTest.aird
tests/data/melodymodel/5_0/MelodyModelTest.capella
tests/test_model_layers.py

Fix port exchange items

---

capellambse/model/crosslayer/capellacommon.py
capellambse/model/crosslayer/fa.py
capellambse/model/layers/ctx.py
capellambse/model/layers/la.py
capellambse/model/layers/oa.py
capellambse/model/layers/pa.py
docs/capella-python-api/capella-python-api.aird
docs/capella-python-api/capella-python-api.capella
tests/data/melodymodel/5_0/MelodyModelTest.afm
tests/data/melodymodel/5_0/MelodyModelTest.aird
tests/data/melodymodel/5_0/MelodyModelTest.capella
tests/test_model_layers.py

this implements a solution for #29

Fix function state rels #29

---

capellambse/model/crosslayer/cs.py
capellambse/model/crosslayer/fa.py
capellambse/model/layers/pa.py
docs/capella-python-api/capella-python-api.aird
docs/capella-python-api/capella-python-api.capella
tests/test_layers_pa.py
tests/test_xlayer_cs.py

* PhysicalLink now has accessors for physical paths and allocated exchanges
* introduced PhysicalPath
* PhysicalPath now has accessors for involved links and allocated exchanges
* PhysicalArchitecture now has accessors for all_physical_paths and all_component_Exchanges
* added tests and test items for all new features
* updated API model

Implemented functionality for #49

---

capellambse/model/crosslayer/capellacommon.py
tests/data/melodymodel/5_0/Melody Model Test.capella
tests/test_xlayer_common.py

Add attributes for realizing and realized states

---

capellambse/aird/capstyle.py
capellambse/aird/diagram.py
capellambse/aird/vector2d.py
capellambse/model/crosslayer/cs.py
capellambse/model/crosslayer/fa.py
capellambse/model/layers/ctx.py
capellambse/model/layers/la.py
capellambse/model/layers/oa.py
capellambse/model/layers/pa.py
capellambse/svg/decorations.py
capellambse/svg/drawing.py
capellambse/svg/generate.py
capellambse/svg/style.py
tests/data/melodymodel/5_0/Melody Model Test.aird
tests/data/melodymodel/5_0/Melody Model Test.capella
tests/test_model_layers.py
tests/test_svg.py

This pull-request adds default styling of OAB, SAB, PAB and OAIB diagrams and fixes a bug on box snapping where a port box would snap to a faulty side when positioning the port box to close to a corner. Furthermore an additional abstract class for Functions was added to remove unnecessary code duplication such that the package attribute could be added to it.
Then the port attribute was added to AbstractComponent and another special case PhysicalPort was added to Component.

Generalize layers

---

capellambse/model/diagram.py

With it, diagrams and corresponding uuid can be listed.

Added method _short_html_ to class AbstracDiagram

---

capellambse/extensions/reqif.py
capellambse/extensions/reqif/__init__.py
capellambse/extensions/reqif/elements.py
capellambse/extensions/reqif/exporter.py
capellambse/loader/xmltools.py
tests/test_reqif.py

Implement basic ReqIF export for a selected requirements module in Capella.

Reqif exporter

---

capellambse/__init__.py
capellambse/loader/__init__.py
capellambse/loader/core.py
capellambse/loader/filehandler/__init__.py
capellambse/model/__init__.py
capellambse/model/common/accessors.py
capellambse/model/common/element.py
capellambse/model/crosslayer/information/datavalue.py
tests/__init__.py
tests/test_reqif.py

This is a loose collection of various smaller changes and features that will make developing software with `capellambse` a little bit easier. Most of the new features are needed by internal projects, but it makes more sense to upstream them for the benefit of the wider community.

Various minor QoL changes / features

---

capellambse/loader/xmltools.py
capellambse/model/crosslayer/information/datavalue.py

crosslayer: set return type to default value

---

capellambse/loader/filehandler/gitfilehandler.py

See commit messages for detailed description.

#44 Improve detection of Git LFS files

---

CONTRIBUTING.md
capellambse/loader/filehandler/__init__.py
capellambse/loader/filehandler/gitfilehandler.py

This PR addresses the issues brought forward in #101:
- Update the code style guidelines on documenting overridden methods
- Add documentation about class parameters

#101 Improve documentation of the `GitFileHandler`

---

capellambse/loader/xmltools.py
capellambse/model/diagram.py
tests/test_model_layers.py

PR #116 ("Improve handling of HTML attributes in the model") introduced a few issues that went undetected by the tests and review. This PR fixes them.

Fix issues introduced with #116

---

capellambse/extensions/reqif/elements.py
capellambse/loader/xmltools.py
capellambse/model/common/accessors.py
capellambse/model/common/element.py
capellambse/model/layers/pa.py
tests/data/writemodel/WriteTestModel.afm
tests/data/writemodel/WriteTestModel.aird
tests/data/writemodel/WriteTestModel.capella
tests/test_model_creation_deletion.py
tests/test_reqif.py

Minor improvements to create api

---

capellambse/svg/style.py
capellambse/svg/symbols.py
tests/data/melodymodel/5_0/Melody Model Test.aird
tests/test_svg.py

Added missing SystemAnalysis root component symbol

---

capellambse/aird/capstyle.py
capellambse/model/layers/la.py
capellambse/model/layers/pa.py

- Standardize allocated_functions attribute of components across all layers.
- Copied styles for SystemActor and SystemHumanActor from [MCB].

Minor fixes

---

.github/workflows/build-test-publish.yml
capellambse/__init__.py
capellambse/cli_helpers.py
capellambse/extensions/reqif/elements.py
capellambse/helpers.py
capellambse/loader/xmltools.py
capellambse/model/__init__.py
capellambse/model/common/accessors.py
capellambse/model/common/element.py
capellambse/model/crosslayer/capellacommon.py
capellambse/model/crosslayer/cs.py
capellambse/model/crosslayer/fa.py
capellambse/model/crosslayer/information/__init__.py
capellambse/model/layers/ctx.py
capellambse/model/layers/la.py
capellambse/model/layers/oa.py
capellambse/model/layers/pa.py
capellambse/repl.py
pyproject.toml
tests/conftest.py
tests/test_cli_helpers.py
tests/test_model_layers.py
tests/test_xlayer_cs.py
tests/test_xlayer_information.py

This PR contains several smaller and larger fixes for issues that have become apparent during development of #145. As they're not dependent on functionality introduced there, they have been extracted from that branch to be merged into `master` earlier.

Suite of fixes to the `MelodyModel` API

---

capellambse/model/crosslayer/interaction.py
capellambse/model/layers/ctx.py
capellambse/model/layers/oa.py

feat(model): Add reverse attributes to Capabilities and Missions

---

capellambse/model/crosslayer/capellacommon.py
tests/data/melodymodel/5_0/Melody Model Test.aird
tests/data/melodymodel/5_0/Melody Model Test.capella
tests/test_model_layers.py

This should solve the issue from #170.

Add `StateTransition.effects`

---

capellambse/extensions/reqif/elements.py
capellambse/model/common/accessors.py
capellambse/model/crosslayer/fa.py
capellambse/model/layers/la.py
capellambse/model/layers/pa.py
tests/test_model_layers.py

For details, please see the individual commits.

Accessor improvements

---

capellambse/model/crosslayer/capellacommon.py
tests/data/melodymodel/5_2/Melody Model Test.capella
tests/test_xlayer_common.py

feat: Add `entries` and `exits` attribute to `capellacommon.State`s

---

capellambse/loader/core.py

This PR introduces the new (hidden) keyword-only argument `ignore_duplicate_uuids_and_void_all_warranties`. With it set, duplicate UUIDs are logged as warnings instead of raised as exceptions. For additional safety, the `save()` method also requires additional confirmation with the `i_have_a_recent_backup` keyword-only argument.

Allow ignoring CorruptModelError from duplicate UUIDs

---

capellambse/_diagram_cache.py
capellambse/loader/core.py
capellambse/model/__init__.py

To review this PR incl. running the code the reviewer needs one or more local Capella bundle(s) and Docker image(s) providing a Capella CLI.
Contact the PR author to get according Docker images.
> **Note**
> It is planned to add tests in the near future

Native diagram cache update function

---

capellambse/__init__.py
capellambse/auditing.py
capellambse/extensions/reqif/_capellareq.py
capellambse/extensions/reqif/_requirements.py
capellambse/loader/xmltools.py
capellambse/model/__init__.py
capellambse/model/common/__init__.py
capellambse/model/common/accessors.py
capellambse/model/common/element.py
capellambse/model/common/properties.py
capellambse/model/crosslayer/cs.py
capellambse/model/crosslayer/fa.py
capellambse/model/crosslayer/information/__init__.py
capellambse/model/crosslayer/information/datavalue.py
capellambse/model/crosslayer/interaction.py
capellambse/model/layers/pa.py
docs/source/examples/10 Declarative Modeling.ipynb
docs/source/index.rst
docs/source/start/audit-events.rst
tests/test_auditing.py
tests/test_reqif.py

This PR introduces new audit events which allow to detect changes made to the model.

Enable auditing changes made to a model

---

capellambse/extensions/metrics/composer.py
docs/source/examples/11 Complexity Assessment.ipynb

Some viewers choke on the uppercased `<SVG>` root element. Make it lowercase to fix it.
Also add a heading to the demo notebook, so that it shows up in the index and sidebar.

Fix complexity badge display

---

capellambse/extensions/reqif/_capellareq.py
capellambse/model/__init__.py
capellambse/model/common/accessors.py
capellambse/model/common/element.py
capellambse/model/crosslayer/capellacore.py
docs/source/examples/08 Property Values.ipynb
docs/source/examples/08 Property Values.ipynb.license
tests/data/melodymodel/5_0/Melody Model Test.capella
tests/test_model_layers.py

Add support for basic property values to the model.
This was originally developed as part of #238.

Basic property value support

---

.github/workflows/lint.yml
.pre-commit-config.yaml
capellambse/aird/_common.py
capellambse/extensions/reqif/elements.py
capellambse/loader/xmltools.py
capellambse/pvmt/core.py
tests/test_cli_helpers.py
tests/test_decl.py
tests/test_model_layers.py
tests/test_model_loading.py

- ci: Fix inconsistent mypy check results
- ci: Add pre-commit hook for pylint

Improve pre-commit CI configuration

---

capellambse/loader/core.py

This PR anticipates a new format for the `.afm` model source file, where the metadata element isn't the root element. I'll try to follow up with an explanation of how this can be achieved via the Capella GUI and add a test model + test case.
Please merge this for getting one of our pipelines green again.

feat: Anticipate extension format in `.afm` modelfile

---

capellambse/model/crosslayer/information/__init__.py

This PR closes #259. I've just changed the commit message to comply with the convential commit format and run all pre-commit hooks.

feat: Add `min_card` and `max_card` to `ExchangeItemElement`

---

capellambse/model/__init__.py
capellambse/model/common/accessors.py
tests/test_model_layers.py

This PR was extracted from #257.

Add function that searches for all references to an object

---

capellambse/model/diagram.py
tests/data/melodymodel/5_0/Melody Model Test.aird
tests/test_diagram.py

Like the docstring suggests: Only visible elements should appear in nodes.

Filter hidden elements from nodes

---

capellambse/filehandler/git.py
capellambse/helpers.py
tests/test_helpers.py
tests/test_model_loading.py

This fixes an issue where the invoked git process would return an error if a parallel process was already performing some task within the repo (like fetching updates). Instead, we now use an additional `capellambse.lock` file within the repo directory which we can `flock` to make sure that only one git instance will be called at a time.
This `flock` based approach works regardless of which parallelization method is used, i.e. thread-based and process-based both work fine.

Lock the repo during calls to git

---

capellambse/model/crosslayer/cs.py

added links attribute to PhysicalPort

---

capellambse/svg/drawing.py

Before this PR:
After this PR:
Solves #283.

Incorporate icon size into label positioning

---

capellambse/_diagram_cache.py

Somehow Capella's SVG writer sets `fill` and `stroke` to `black` on the root SVG element. These styles get inherited from `clipPath` elements which might span the whole SVG viewbox. In a PDF the inheritance is considered such that instead of a diagram, only a black box is rendered.
This commit fixes the issue.

fix(diargam_cache): Add `_sanitize_svg` with new overrides

---

capellambse/model/common/element.py

Skip displaying ReferenceSearchingAccessor attributes

---

capellambse/cli_helpers.py
capellambse/repl.py

This PR extends `enumerate_known_models` to search the user config dir for capellambse in addition to the package installation directory. This allows users to more conveniently store model information for use with CLI tools around capellambse.
Resolves #293

Search for known models in user config dir

---

capellambse/helpers.py
tests/test_helpers.py

Helps modifying Markup HTML arbitrarily.

Factor out HTML fragment processing

---

capellambse/model/diagram.py

Is needed [for #48 in context-diagrams](https://github.com/DSD-DBS/capellambse-context-diagrams/pull/48).

Fix `AbstractDiagram.nodes`

---

capellambse/_native.py

Checking whether using the inbuild docker commands to copy files fixes the permission error when trying to copy the diagram cache to the host system

Copy files into / out of docker container

---

capellambse/loader/core.py

With the new entrypoint logic introduced in #310, additional keyword-only arguments that needed to be passed to the `get_filehandler` function would get lost. This could cause inexplicable follow-up errors like "permission denied" or "file not found", when it dropped login credentials or a VCS revision argument.
This PR also changes the `ignore_duplicate_uuids_and_void_all_warranties` argument to be a "proper" keyword-only argument to MelodyLoader, instead of pulling it from `kwargs`. This caused pylint to recognize the `kwargs` as being used, and therefore it did not issue an "unused" warning.
Thanks to @MoritzWeber0 for finding and reporting this!

Pass MelodyLoader's `**kwargs` on to `get_filehandler`

---

capellambse/filehandler/git.py

On many systems, such as MacOS and Windows, a default Git credential helper is defined. The credential helper is set in the Git configuration with the credential.helper option.
According to the official Git documentation (https://git-scm.com/docs/gitcredentials), the `GIT_ASKPASS` environment variable is ignored when a credential helper is configured.
Therefore, the username and password arguments were ignored when a credential.helper was set. This was not intentional, as the user obviously wants to use the credentials passed.

fix(filehandler): Ignore Git `credential.helper` for passed credentials

---

capellambse/cli_helpers.py
capellambse/repl.py
ci-templates/README.rst
ci-templates/github/README.rst
ci-templates/github/model-complexity-badge/action.yml

you can see the working usage here: https://github.com/DSD-DBS/coffee-machine/pull/7
resolves this issue for github https://github.com/DSD-DBS/py-capellambse/issues/299

Add Github CI template for model badge

---

capellambse/model/crosslayer/cs.py
capellambse/model/crosslayer/fa.py
tests/data/melodymodel/5_0/Melody Model Test.aird
tests/data/melodymodel/5_0/Melody Model Test.capella
tests/test_model_layers.py

Adds realizing/realized links between CEX, and allows multiple CEX → PhysicalPath allocations.

More missing CEX attributes

---

capellambse/filehandler/gitlab_artifacts.py

- Work around Gitlab bug #414807 (c91f37fba3f85977f7dc24e24595bc8597fd40c2)
- Improve documentation and error messages (28efe54be46afc3a27122dba720cf49f6210a50d)

Improvements to the Gitlab Artifacts file handler

---

capellambse/diagram/_styleclass.py
capellambse/diagram/capstyle.py
capellambse/model/crosslayer/capellacore.py
capellambse/model/crosslayer/information/__init__.py
capellambse/svg/decorations.py

This is needed for [context-diagrams #55](https://github.com/DSD-DBS/capellambse-context-diagrams/pull/55) to properly work.

Add missing attributes and default styling

---

capellambse/svg/drawing.py

Fix false-positive error about missing symbols

---

README.rst

This should help with discoverability of those projects.

Add a "Related projects" section to README

---

capellambse/loader/core.py

We briefly talked about this topic before, and I vaguely recall that, in the end, we all kinda agreed on this. @ewuerger  
<sup>(I might be wrong though.)</sup>

Don't fall back to making a random UUID

---

capellambse/model/layers/ctx.py
capellambse/model/layers/la.py

"involved_in" accessor allows for Functions (System, Logical) to see in which Capabilities it is involved in.

Implement System/LogicalFunction.involved_in

---

capellambse/filehandler/git.py
tests/test_filehandler_git.py
tests/test_model_loading.py

Resolve default Git branch

---

capellambse/model/__init__.py
capellambse/model/common/accessors.py
capellambse/model/crosslayer/cs.py
capellambse/model/crosslayer/fa.py
capellambse/model/layers/ctx.py
capellambse/model/layers/la.py
capellambse/model/layers/oa.py
capellambse/model/layers/pa.py
capellambse/repl.py

This fixes some (but not (yet) all) of the problems described in #400.

Fixes to the metamodel

---

capellambse/_namespaces.py
capellambse/helpers.py
capellambse/loader/core.py
capellambse/model/__init__.py
capellambse/model/common/element.py
capellambse/pvmt/validation.py
tests/test_model_creation_deletion.py

One more piece to solving #400.

Automatic namespace management

---

capellambse/svg/decorations.py
capellambse/svg/drawing.py

Fix symbol labels overlapping into other symbols.

Fix symbol label wrapping

---

capellambse/model/common/properties.py
capellambse/model/crosslayer/fa.py
capellambse/model/crosslayer/information/__init__.py
capellambse/model/modeltypes.py
docs/source/start/specifying-models.rst
scripts/generate_enums.py

Also add all the missing enum definitions.

Fix de-/serialization of enums

---

capellambse/_diagram_cache.py

This PR proposes a post-processing step in the diagram cache which gets the x_min, x_max, y_min, y_max limits for the bounding box of found content. It will then adjust the viewBox, canvas size and white background rectangle (another custom post-process step) so that the found content appears to be moved to the top left corner of the canvas whereby the canvas is cropped to surround the content with a 10 px margin.
Considered are the following shape kinds/ XML tags for now:
circle, ellipse, image, line, polygon, polyline, rect, and text.
Since this approach covers basic scenarios and is not considering all possible / specified (XML spec) kinds of shapes and/ or imaginable transformations (translate, rotate, scale), nested coordinate systems etc.,  the post-process step will be applied when …

Minimize SVG viewboxes when creating diagram cache

---

capellambse/diagram/_styleclass.py

This adds the `OperationalActor` styleclass.

feat(diagram): Add styleclass handler for `Entity`

---

capellambse/_namespaces.py
capellambse/loader/core.py
capellambse/loader/exs.py

This PR fixes a few issues around the "automatic namespace management" introduced with v0.5.58.

Fix namespace management

---

capellambse/filehandler/git.py

This commit changes the Git file handler to check out the work tree as real files. This simplifies some operations drastically, as it allows us to rely more on the porcelain layer and specifically Git's index. By having all files of the given commit checked out, it also forces all blobs to be made available locally, and therefore resolves #427.
As part of this change, the base directory for the work trees was moved from the system temporary directory to the user cache directory. Modern Linux systems have the former reside in a ramdisk, which is not a good place to store (potentially huge) model files.

Git: Check out the work tree

---

capellambse/diagram/capstyle.py
capellambse/svg/drawing.py
capellambse/svg/symbols.py

- Fixes #441
- Added a filled arrow mark
- Improved styles of some edge types to better match Capella

Fix marker styling

---

capellambse/diagram/_diagram.py

The "oblique" algorithm for vector snapping on Boxes used to ignore the `source` point, and would instead always snap to the closest point on the border. Now, if we do have a source, we take the incoming edge's direction into account when calculating the border intersection points.

Implement two-point oblique vector snapping

---

capellambse/diagram/_diagram.py

fix: Snap on first intersect

---

capellambse/metamodel/cs.py
capellambse/metamodel/fa.py
capellambse/metamodel/la.py
capellambse/metamodel/pa.py
capellambse/metamodel/sa.py

Add component and functional exchange categories

---

capellambse/metamodel/fa.py
tests/data/melodymodel/5_0/Melody Model Test.capella
tests/test_model_layers.py

The attribute is missing on `FunctionalChain` and `OperationalProcess`. A test was added too.

Add pre-/postcondition to FunctionalChain

---

capellambse/extensions/pvmt/_config.py
tests/test_model_pvmt.py

Fixes #484 
***Stacked on #486***

Fix applying Enumeration property values with PVMT

---

src/capellambse/metamodel/pa.py

Just for `components` in `PhysicalComponent`.

Remove duplicates in `PhysicalComponent.components`

---

src/capellambse/filehandler/http.py

Some servers may send a different code than 404 if a file doesn't exist for some reason or another. For example, when requesting a PNG file from a diagram cache that only allows SVG, the cache server may respond with 400 Bad Request instead. Other servers may respond with 410 Gone if a file is requested that used to exist but has been deleted (because its retention period expired, for example).

Treat more HTTP response codes as "not found"

---

src/capellambse/extensions/filtering.py

Use a simple property and `ElementList.map()` instead of a specialized, single-use Accessor subclass.

Simplify 'ModelElement.filtering_criteria'
